CREATE SCHEMA DEMO;
CREATE TABLE IF NOT EXISTS ALERT_TBL (
	ALERT_ID NUMBER(38,0) DEFAULT ALERT_TBL_SEQ.NEXTVAL,
	EVENT_TIME TIMESTAMP_NTZ(9),
	COMMIT_TIME TIMESTAMP_NTZ(9),
	ALERT_RULE_ID VARCHAR(100),
	ALERT_TYPE VARCHAR(100),
	SOURCE_NM VARCHAR(200),
	CONTEXT VARCHAR(100),
	TRIGGER_TYPE VARCHAR(100),
	INSERTION_TS TIMESTAMP_NTZ(9)
);
